import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Layout from "@/components/layout/Layout";
import WeatherPage from "./weather_page";
import { useEffect, useState } from "react";
import { useRecoilState } from "recoil";
import {
  currentLocationLatitude,
  currentLocationLongitude,
} from "@/components/states/current_location_state";

export default function Home() {
  const [latitude, setLatitude] = useRecoilState(currentLocationLatitude);
  const [longitude, setLongitude] = useRecoilState(currentLocationLongitude);
  const [loaded, setLoaded] = useState<boolean>(false);

  useEffect(() => {
    const locationFail = (err: any) => {
      alert(`ERROR(${err.code}): ${err.message}`);
    };
    const locationSuccess = async (pos: any) => {
      const coordinates = await pos.coords;
      setLatitude(coordinates.latitude);
      setLongitude(coordinates.longitude);
      setLoaded(true);
    };
    const getLocation = async () => {
      try {
        if (!navigator.geolocation) {
          alert("위치 정보가 지원되지 않습니다");
        }

        navigator.geolocation.getCurrentPosition(locationSuccess, locationFail);
      } catch (err) {
        alert(err);
      }
    };
    getLocation();
  }, [setLatitude, setLongitude]);
  return (
    <>
      <Head>
        <title>Weather App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>{loaded && <WeatherPage />}</Layout>
    </>
  );
}
